
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ru.hostco.sumz.save.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-01-29T21:18:37.016+06:00
 * Generated source version: 3.1.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "SaveService",
                      portName = "SavePort",
                      targetNamespace = "http://www.hostco.ru/sumz/save/service",
                      wsdlLocation = "file:/D:/okp_svn/Бизнес-проекты/СУМЗ%20-%20Автоматизация%20весов/Программирование/Приложения/sumz-soap-save/src/main/resources/wsdl-save/Save.wsdl",
                      endpointInterface = "ru.hostco.sumz.save.service.SaveType")
                      
public class SavePortImpl implements SaveType {

    private static final Logger LOG = Logger.getLogger(SavePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ru.hostco.sumz.save.service.SaveType#refreshTrain(ru.hostco.sumz.save.RefreshTrainR  parameter )*
     */
    public ru.hostco.sumz.save.RefreshTrainA refreshTrain(ru.hostco.sumz.save.RefreshTrainR parameter) { 
        LOG.info("Executing operation refreshTrain");
        System.out.println(parameter);
        try {
            ru.hostco.sumz.save.RefreshTrainA _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.hostco.sumz.save.service.SaveType#savePlatform(ru.hostco.sumz.save.SavePlatformR  parameter )*
     */
    public ru.hostco.sumz.save.SavePlatformA savePlatform(ru.hostco.sumz.save.SavePlatformR parameter) { 
        LOG.info("Executing operation savePlatform");
        System.out.println(parameter);
        try {
            ru.hostco.sumz.save.SavePlatformA _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.hostco.sumz.save.service.SaveType#refreshAuto(ru.hostco.sumz.save.RefreshAutoR  parameter )*
     */
    public ru.hostco.sumz.save.RefreshAutoA refreshAuto(ru.hostco.sumz.save.RefreshAutoR parameter) { 
        LOG.info("Executing operation refreshAuto");
        System.out.println(parameter);
        try {
            ru.hostco.sumz.save.RefreshAutoA _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.hostco.sumz.save.service.SaveType#saveTrain(ru.hostco.sumz.save.SaveTrainR  parameter )*
     */
    public ru.hostco.sumz.save.SaveTrainA saveTrain(ru.hostco.sumz.save.SaveTrainR parameter) { 
        LOG.info("Executing operation saveTrain");
        System.out.println(parameter);
        try {
            ru.hostco.sumz.save.SaveTrainA _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.hostco.sumz.save.service.SaveType#saveAuto(ru.hostco.sumz.save.SaveAutoR  parameter )*
     */
    public ru.hostco.sumz.save.SaveAutoA saveAuto(ru.hostco.sumz.save.SaveAutoR parameter) { 
        LOG.info("Executing operation saveAuto");
        System.out.println(parameter);
        try {
            ru.hostco.sumz.save.SaveAutoA _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
