package ru.hostco.sumz.save.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-01-29T21:18:37.184+06:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "SaveService", 
                  wsdlLocation = "file:/D:/okp_svn/Бизнес-проекты/СУМЗ%20-%20Автоматизация%20весов/Программирование/Приложения/sumz-soap-save/src/main/resources/wsdl-save/Save.wsdl",
                  targetNamespace = "http://www.hostco.ru/sumz/save/service") 
public class SaveService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.hostco.ru/sumz/save/service", "SaveService");
    public final static QName SavePort = new QName("http://www.hostco.ru/sumz/save/service", "SavePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/okp_svn/Бизнес-проекты/СУМЗ%20-%20Автоматизация%20весов/Программирование/Приложения/sumz-soap-save/src/main/resources/wsdl-save/Save.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SaveService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/okp_svn/Бизнес-проекты/СУМЗ%20-%20Автоматизация%20весов/Программирование/Приложения/sumz-soap-save/src/main/resources/wsdl-save/Save.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SaveService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SaveService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaveService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SaveService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SaveService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SaveService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SaveType
     */
    @WebEndpoint(name = "SavePort")
    public SaveType getSavePort() {
        return super.getPort(SavePort, SaveType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaveType
     */
    @WebEndpoint(name = "SavePort")
    public SaveType getSavePort(WebServiceFeature... features) {
        return super.getPort(SavePort, SaveType.class, features);
    }

}
