package ru.hostco.sumz.save.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2016-01-29T21:18:37.177+06:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.hostco.ru/sumz/save/service", name = "SaveType")
@XmlSeeAlso({ru.hostco.sumz.save.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SaveType {

    /**
     * Обновление взвешевания ЖД
     */
    @WebMethod(operationName = "RefreshTrain", action = "urn:RefreshTrain")
    @WebResult(name = "RefreshTrain_A", targetNamespace = "http://www.hostco.ru/sumz/save", partName = "parameter")
    public ru.hostco.sumz.save.RefreshTrainA refreshTrain(
        @WebParam(partName = "parameter", name = "RefreshTrain_R", targetNamespace = "http://www.hostco.ru/sumz/save")
        ru.hostco.sumz.save.RefreshTrainR parameter
    );

    /**
     * Сохранение взвешевания П
     */
    @WebMethod(operationName = "SavePlatform", action = "saveP")
    @WebResult(name = "SavePlatform_A", targetNamespace = "http://www.hostco.ru/sumz/save", partName = "parameter")
    public ru.hostco.sumz.save.SavePlatformA savePlatform(
        @WebParam(partName = "parameter", name = "SavePlatform_R", targetNamespace = "http://www.hostco.ru/sumz/save")
        ru.hostco.sumz.save.SavePlatformR parameter
    );

    /**
     * Обновление взвешевания Авто
     */
    @WebMethod(operationName = "RefreshAuto", action = "RefreshAuto")
    @WebResult(name = "RefreshAuto_A", targetNamespace = "http://www.hostco.ru/sumz/save", partName = "parameter")
    public ru.hostco.sumz.save.RefreshAutoA refreshAuto(
        @WebParam(partName = "parameter", name = "RefreshAuto_R", targetNamespace = "http://www.hostco.ru/sumz/save")
        ru.hostco.sumz.save.RefreshAutoR parameter
    );

    /**
     * Сохранение взвешевания ЖД
     */
    @WebMethod(operationName = "SaveTrain", action = "saveT")
    @WebResult(name = "SaveTrain_A", targetNamespace = "http://www.hostco.ru/sumz/save", partName = "parameter")
    public ru.hostco.sumz.save.SaveTrainA saveTrain(
        @WebParam(partName = "parameter", name = "SaveTrain_R", targetNamespace = "http://www.hostco.ru/sumz/save")
        ru.hostco.sumz.save.SaveTrainR parameter
    );

    /**
     * Сохранение взвешевания АВТО
     */
    @WebMethod(operationName = "SaveAuto", action = "saveA")
    @WebResult(name = "SaveAuto_A", targetNamespace = "http://www.hostco.ru/sumz/save", partName = "parameter")
    public ru.hostco.sumz.save.SaveAutoA saveAuto(
        @WebParam(partName = "parameter", name = "SaveAuto_R", targetNamespace = "http://www.hostco.ru/sumz/save")
        ru.hostco.sumz.save.SaveAutoR parameter
    );
}
